--!native

local RunService = game:GetService("RunService")

local packetIDs = require(script.Parent.Parent.namespaces.packetIDs)
local queryIDs = require(script.Parent.Parent.namespaces.queryIDs)
local readRefs = require(script.Parent.readRefs)
local types = require(script.Parent.Parent.types)
local bufferWriter = require(script.Parent.bufferWriter)

local alloc = bufferWriter.alloc
local u8 = bufferWriter.u8
local load = bufferWriter.load

local packetRef = packetIDs.ref()
local queryRef = queryIDs.ref()
local freeThread: thread?

local function functionPasser(callback, ...)
	local aquiredThread = freeThread
	freeThread = nil
	callback(...)
	freeThread = aquiredThread
end

local function yielder()
	while true do
		functionPasser(coroutine.yield())
	end
end

local function runListener(listener, packet, ...)
	if freeThread == nil then
		freeThread = coroutine.create(yielder)
		coroutine.resume(freeThread :: thread)
	end

	task.spawn(freeThread :: thread, listener.Callback, ...)
end

local function runQueryListener(listener: types.QueryListener<any, any>, query, ...)
	local result
	local callbackEnded: boolean = false
	local ts = tick()
	if freeThread == nil then
		freeThread = coroutine.create(yielder)
		coroutine.resume(freeThread :: thread)
	end

	task.spawn(freeThread :: thread, function(...)
		result, callbackEnded = listener.Callback(...), true
	end, ...)

	repeat
		task.wait()
	until callbackEnded or (tick() - ts) > 10

	if callbackEnded == false then
		warn("query hung for 10 seconds or otherwise failed, returning nil.")
	end

	return result
end

local function create()
	return {
		cursor = 0,
		size = 256,
		references = {},
		buff = buffer.create(256),
	}
end

local function dump(channel: types.channelData): (buffer, { unknown }?)
	local cursor = channel.cursor
	local dumpBuffer = buffer.create(cursor)

	buffer.copy(dumpBuffer, 0, channel.buff, 0, cursor)

	return dumpBuffer, if #channel.references > 0 then channel.references else nil
end

local function clearListeners(packetOrQuery, listeners: { types.Listener<any> })
	for _, listener in listeners do
		packetOrQuery.disconnect(listener)
	end
end

return function(
	incomingBuffer: buffer,
	references: { [number]: unknown }?,
	player: Player?,
	readType: string?,
	id: number?
)
	local length = buffer.len(incomingBuffer)
	local readCursor = 0
	readType = readType or "packet"

	readRefs.set(references)

	while readCursor < length do
		local readablePacketOrQuery

		if readType == "packet" then
			readablePacketOrQuery = packetRef[buffer.readu8(incomingBuffer, readCursor)]
		elseif readType == "query" then
			readablePacketOrQuery = queryRef[buffer.readu8(incomingBuffer, readCursor)]
		else
			error("readType not valid.")
		end

		if not readablePacketOrQuery then
			error(
				"No readable entity found for ID: "
					.. buffer.readu8(incomingBuffer, readCursor)
					.. " for type: "
					.. readType
			)
		end

		readCursor += 1

		local value, valueLength

		if readType == "query" then
			if RunService:IsServer() then
				value, valueLength = readablePacketOrQuery.requestReader(incomingBuffer, readCursor)
			elseif RunService:IsClient() then
				value, valueLength = readablePacketOrQuery.responseReader(incomingBuffer, readCursor)
			end
		elseif readType == "packet" then
			value, valueLength = readablePacketOrQuery.reader(incomingBuffer, readCursor)
		end

		readCursor += valueLength

		-- Triggered OnceCallback listeners to remove.
		-- we can't remove them immediately as that causes
		-- issues if we have multiple listeners to iterate
		local listenersToDisconnect: { types.Listener<any> } = {}

		if readType == "packet" then
			for _, listener in readablePacketOrQuery.getListeners() do
				if typeof(listener) == "table" then
					runListener(listener, readablePacketOrQuery, value, player)

					if listener.OnceCallback == true then
						table.insert(listenersToDisconnect, listener)
					end
				else
					error("Listener type not recognised for packet: " .. typeof(listener))
				end
			end
			clearListeners(readablePacketOrQuery, listenersToDisconnect)
		elseif readType == "query" then
			if RunService:IsServer() then
				for _, listener in readablePacketOrQuery.getListeners() do
					local response

					if typeof(listener) == "table" and listener.Disconnecting ~= true then
						-- mark it as disconnecting so it doesn't get triggered twice
						-- should the callback take a while and the packet is invoked
						-- more than once.
						if listener.OnceCallback == true then
							listener.Disconnecting = true
							table.insert(listenersToDisconnect, listener)
						end

						response = runQueryListener(listener, readablePacketOrQuery, value, player)
					else
						error("Listener type not recognised for query: " .. typeof(listener))
					end

					local func = create()
					func = load(func)

					alloc(1)
					u8(id)
					readablePacketOrQuery.responseWriter(response)

					func = bufferWriter.export()

					if func.cursor > 0 then
						local dumpBuffer, reference = dump(func)

						clearListeners(readablePacketOrQuery, listenersToDisconnect)

						return dumpBuffer, reference
					end
				end
				print("not returning ???")
			elseif RunService:IsClient() then
				return value
			end
		end
	end
end
